test count = 4
test number = 0
test name = 'UnknownExceptionTest'
test result = 'failed'
test abort reason = '(null)'
test todo = 0
test todo reason = '(null)'
test done
test number = 1
test name = 'StdExceptionTest'
test result = 'failed'
test abort reason = 'This should fail'
test todo = 0
test todo reason = '(null)'
test done
test number = 2
test name = 'PassingDestructorTest'
created Foo with 42
destroyed Foo with 42
test result = 'passed'
test abort reason = '(null)'
test todo = 0
test todo reason = '(null)'
test done
test number = 3
test name = 'FailingDestructorTest'
created Foo with 42
destroyed Foo with 42
test result = 'failed'
test abort reason = '(null)'
test todo = 0
test todo reason = '(null)'
test done
testing done
